### ISSUE TITLE
Create sifter not working with Create 6.0.7

### ISSUE THREAD

**Issue by DaGamer5000** [oierbravo/mechanicals-wiki#2]
The mod fails to load because of an class that was probably removed.
This is what it says in the logs:
 _java.lang.NoClassDefFoundError: com.simibubi.create.foundation.data.recipe.CompatMetals_,
So i would really appreciate if you updated the mod to work with Create 6.0.7!

**Comment by oierbravo** [comment]
Duplicate of https://github.com/oierbravo/createsifter/issues/102
